FROM golang:latest AS builder

RUN mkdir /app
ADD . /app

WORKDIR /app

# install psql
RUN apt-get update
RUN apt-get -y install postgresql-client

# make wait-for-postgres.sh executable
RUN chmod +x wait-for-postgres.sh

# build go app
RUN mkdir /.bin
RUN go mod download
RUN GOOS=linux CGO_ENABLED=0 go build -o ./.bin/app ./cmd/app/main.go

FROM alpine:latest

WORKDIR /root

COPY --from=builder /app/.bin/app .

CMD ["./app"]