FROM golang:latest AS builder

RUN mkdir /app
ADD . /app

WORKDIR /app

# build go logger
RUN mkdir /.bin
RUN go mod download
RUN GOOS=linux CGO_ENABLED=0 go build -o ./.bin/logger ./cmd/logger/main.go

FROM alpine:latest

WORKDIR /root

COPY --from=builder /app/.bin/logger .

CMD ["./logger"]