version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    container_name: 'user_app'
    command: ./wait-for-postgres.sh pgdb ./app
    ports:
      - 8080:8080
    depends_on:
      - logger
    environment:
      - DB_PASSWORD=qwerty
    networks:
      - internal

  logger:
    build:
      context: .
      dockerfile: Dockerfile-logger
    container_name: 'user_logger'
    ports:
      - 8081:8081
    depends_on:
      - clickhouse
    networks:
      - internal

  clickhouse:
    image: yandex/clickhouse-server
    hostname: user_clickhouse
    container_name: 'user_clickhouse'
    ports:
      - 8125:8123
      - 9002:9000
    volumes:
      - ./.clickhouse/data:/var/lib/clickhouse
      - ./api/clickhouse/migrations:/var/lib/clickhouse/migrations
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - rabbitmq
    networks:
      - internal

  rabbitmq:
    image: rabbitmq:3.9.13-management
    container_name: 'user_rabbitmq'
    ports:
      - 5674:5672
      - 15674:15672
    depends_on:
      - redis
    volumes:
      - ./.rabbitmq/data:/var/lib/rabbitmq
    networks:
      - internal

  redis:
    image: redis:6.2-alpine
    container_name: 'user_redis'
    ports:
      - 6381:6379
    depends_on:
      - pgdb
    networks:
      - internal

  pgdb:
    restart: always
    image: postgres:13
    container_name: 'user_postgres'
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=postgres
    ports:
      - 5434:5432
    networks:
      - internal

networks:
  internal:
    driver: bridge
