port: "8080"

db:
    username: "postgres"
    password: "qwerty"
    host: "pgdb" #pgdb #localhost
    port: "5432" #5432 #5434
    name: "postgres"
    sslmode: "disable"

cache:
    host: "redis" #redis #localhost
    port: "6379" #6379 #6381
    password: ""
    db: 0

queue:
    host: "rabbitmq" #rabbitmq #localhost #user_rabbitmq
    port: "5672" #5672 #5674
    username: "guest"
    password: "guest"
    queuename: "UserQueue"

clickhouse:
    host: "clickhouse" #clickhouse #localhost #user_clickhouse
    port: "9000" #9000 #9002
    username: "default"
    dbname: "db_user"
    password: ""

messages:
    responses:
        added_successfully: "новый пользователь с id (#%d) успешно добавлен"    
        removed_successfully: "пользователь с id (#%d) успешно удален"    
    errors:
        default: "неизвестная ошибка"
        invalid_email: "неверный формат (username@example.com) поля email"
        invalid_input_data: "неверный диапазон (от 18 до 120) поля age или формат (username@example.com) поля email"
        already_exists: "пользователь с таким email уже существует"
        not_exists: "пользователь с таким email не существует"