port: "8080"

db:
    username: "postgres"
    password: "qwerty"
    host: "localhost" #pgdb
    port: "5434" #5432
    name: "postgres"
    sslmode: "disable"

cache:
    host: "localhost"
    port: "6381" #6379
    password: ""
    db: 0

queue:
    host: "localhost"
    port: "5674" #5672
    username: "guest"
    password: "guest"
    queuename: "UserQueue"

clickhouse:
    host: "127.0.0.1"
    port: "9002" #9000
    username: "default"
    dbname: "db_user"
    password: ""

messages:
    responses:
        added_successfully: "новый пользователь с id (#%d) успешно добавлен"    
        removed_successfully: "пользователь с id (#%d) успешно удален"    
    errors:
        default: "неизвестная ошибка"
        invalid_email: "неверный формат (username@example.com) поля email"
        invalid_input_data: "неверный диапазон (от 18 до 120) поля age или формат (username@example.com) поля email"
        already_exists: "пользователь с таким email уже существует"
        not_exists: "пользователь с таким email не существует"